const fs = require('fs'), path = require('path')
// PRIVATE MODE (Oct 4) — individual-tier data-license compliance. 3 files:
//  1. Landing page -> minimal private placeholder (no pricing, no signup,
//     no early-access capture). Old marketing page stays in git history
//     for when business licensing happens.
//  2. /pricing -> redirects home.
//  3. Polygon proxy locked to app-originated requests (it was fully open —
//     anyone could pull market data through the server key).
const writes = [
  { dest: "src/app/page.tsx", content: "/**\n * Landing page \u2014 private-mode placeholder (Oct 4).\n * The marketing site (pricing tiers, early-access capture) is taken down\n * while the platform runs on individual-tier data licenses. Restore the\n * commercial page from git history when moving to business licensing.\n */\n\nimport Link from 'next/link'\n\nexport default function Home() {\n  return (\n    <main style={{\n      minHeight: '100vh', display: 'flex', flexDirection: 'column',\n      alignItems: 'center', justifyContent: 'center', gap: 20,\n      background: '#070b14', color: '#e8f0ff', padding: 24, textAlign: 'center',\n      fontFamily: 'system-ui, -apple-system, sans-serif',\n    }}>\n      <h1 style={{ fontSize: 34, fontWeight: 800, letterSpacing: 1, margin: 0 }}>\n        tr<span style={{ color: '#00e5ff' }}>AI</span>de Zone\n      </h1>\n      <p style={{ maxWidth: 440, lineHeight: 1.7, color: '#8aa0c8', fontSize: 15, margin: 0 }}>\n        A private SPX research project. This is a personal, non-commercial\n        platform \u2014 there are no subscriptions, signups, or services offered.\n      </p>\n      <Link href=\"/sign-in\" style={{\n        marginTop: 8, padding: '10px 26px', borderRadius: 8, fontSize: 14, fontWeight: 600,\n        background: 'rgba(0,229,255,0.1)', border: '1px solid rgba(0,229,255,0.35)',\n        color: '#00e5ff', textDecoration: 'none',\n      }}>\n        Sign in\n      </Link>\n      <p style={{ fontSize: 12, color: '#4a5a78', marginTop: 16 }}>\n        \u00a9 {new Date().getFullYear()} trAIde Zone\n      </p>\n    </main>\n  )\n}\n" },
  { dest: "src/app/pricing/page.tsx", content: "/**\n * Pricing page \u2014 taken down while in private/individual-license mode.\n * Restore from git history when moving to business licensing.\n */\nimport { redirect } from 'next/navigation'\n\nexport default function Pricing() {\n  redirect('/')\n}\n" },
  { dest: "src/app/api/polygon/route.ts", content: "import { NextRequest, NextResponse } from 'next/server'\n\nexport async function GET(req: NextRequest) {\n  // Oct 4: the proxy was fully open \u2014 anyone could pull market data through\n  // the server's key (a redistribution problem under individual-tier data\n  // licensing). Require the request to originate from the app itself.\n  const from = (req.headers.get('origin') || '') + ' ' + (req.headers.get('referer') || '')\n  if (!from.includes('traidezone') && !from.includes('localhost')) {\n    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })\n  }\n\n  const { searchParams } = new URL(req.url)\n  const apiKeyParam = searchParams.get('apiKey')\n  const path = searchParams.get('path')\n  const paginate = searchParams.get('paginate') === 'true'\n\n  if (!path) {\n    return NextResponse.json({ error: 'Missing path' }, { status: 400 })\n  }\n\n  // Use server-side env var \u2014 ignore any client-passed key\n  const apiKey = process.env.POLYGON_API_KEY\n  if (!apiKey) {\n    return NextResponse.json({ error: 'Polygon API key not configured' }, { status: 500 })\n  }\n\n  const base = 'https://api.polygon.io'\n\n  if (!paginate) {\n    const url = `${base}${path}${path.includes('?') ? '&' : '?'}apiKey=${apiKey}`\n    const res = await fetch(url, { cache: 'no-store' })\n    const data = await res.json()\n    return NextResponse.json(data)\n  }\n\n  let allResults: any[] = []\n  let nextPath: string | null = path\n  let pages = 0\n\n  while (nextPath && pages < 25) {\n    const url: string = `${base}${nextPath}${nextPath.includes('?') ? '&' : '?'}apiKey=${apiKey}`\n    const res: Response = await fetch(url, { cache: 'no-store' })\n    const data: any = await res.json()\n\n    if (data.results?.length) allResults = allResults.concat(data.results)\n\n    if (data.next_url) {\n      try {\n        const u: URL = new URL(data.next_url)\n        nextPath = u.pathname + u.search\n      } catch { break }\n    } else {\n      nextPath = null\n    }\n    pages++\n  }\n\n  return NextResponse.json({ status: 'OK', results: allResults, resultsCount: allResults.length, pages })\n}" }
]
let ok = 0
for (const {dest, content} of writes) {
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  fs.writeFileSync(dest + '.tmp', content, 'utf8')
  fs.renameSync(dest + '.tmp', dest)
  console.log('OK ' + dest); ok++
}
console.log('\n' + ok + ' files written (private mode).')
console.log('Next: git add -A && git commit -m "private mode: take down commercial pages, lock data proxy" && git push origin main')
